package br.com.calçados.ui.principal;

import br.com.calçados.ui.clientes.TelaCadastrarCliente;
import br.com.calçados.ui.clientes.TelaConsultarClientes;
import br.com.calçados.ui.produtos.TelaCadastrarProduto;
import br.com.calçados.ui.produtos.TelaConsultarProduto;
import br.com.calçados.ui.venda.TelaFazerVenda;
import br.com.calçados.ui.venda.TelaGerarRelatorio;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

public class TelaPrincipal extends javax.swing.JFrame {

    private Image image;

    public TelaPrincipal() {
        initComponents();
        this.setSize(600,400);
        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            private Image image;
            {
                try {
                    image = ImageIO.read(new File("src/resources/lojacalcados.jpg"));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        cadastrarCliente = new javax.swing.JMenuItem();
        consultarCliente = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenu();
        cadastrarProduto = new javax.swing.JMenuItem();
        consultarProduto = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenu();
        criarComanda = new javax.swing.JMenuItem();
        gerarRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja de Calçados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        menuCliente.setText("Clientes");

        cadastrarCliente.setText("Cadastrar Cliente");
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(cadastrarCliente);

        consultarCliente.setText("Consultar Clientes");
        consultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(consultarCliente);

        jMenuBar1.add(menuCliente);

        menuProduto.setText("Produtos");

        cadastrarProduto.setText("Cadastrar Produto");
        cadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProdutoActionPerformed(evt);
            }
        });
        menuProduto.add(cadastrarProduto);

        consultarProduto.setText("Consultar Produtos");
        consultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarProdutoActionPerformed(evt);
            }
        });
        menuProduto.add(consultarProduto);

        jMenuBar1.add(menuProduto);

        menuVenda.setText("Vendas");

        criarComanda.setText("Fazer Venda");
        criarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarComandaActionPerformed(evt);
            }
        });
        menuVenda.add(criarComanda);

        gerarRelatorio.setText("Gerar Relatorio");
        gerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelatorioActionPerformed(evt);
            }
        });
        menuVenda.add(gerarRelatorio);

        jMenuBar1.add(menuVenda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    TelaCadastrarCliente tCadastrarC = null;
    TelaConsultarClientes tConsultarC = null;
    TelaCadastrarProduto tCadastrarP = null;
    TelaConsultarProduto tConsultarP = null;
    TelaFazerVenda tCriarComanda = null;
    TelaGerarRelatorio tGerarRelatorio = null;

    private void consultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarClienteActionPerformed
        if (tConsultarC == null || !tConsultarC.isDisplayable()) {
            tConsultarC = new TelaConsultarClientes();
            tConsultarC.pack();
            tConsultarC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            tConsultarC.setLocationRelativeTo(null);
            tConsultarC.setVisible(true);
        }
        tConsultarC.toFront();
    }//GEN-LAST:event_consultarClienteActionPerformed

    private void cadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProdutoActionPerformed
        if (tCadastrarP == null || !tCadastrarP.isDisplayable()) {
            tCadastrarP = new TelaCadastrarProduto();
            tCadastrarP.pack();
            tCadastrarP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            tCadastrarP.setLocationRelativeTo(null);
            tCadastrarP.setVisible(true);
        }
        tCadastrarP.toFront();
    }//GEN-LAST:event_cadastrarProdutoActionPerformed

    private void consultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarProdutoActionPerformed
        if (tConsultarP == null || !tConsultarP.isDisplayable()) {
            tConsultarP = new TelaConsultarProduto();
            tConsultarP.pack();
            tConsultarP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            tConsultarP.setLocationRelativeTo(null);
            tConsultarP.setVisible(true);
        }
        tConsultarP.toFront();
    }//GEN-LAST:event_consultarProdutoActionPerformed

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        if (tCadastrarC == null || !tCadastrarC.isDisplayable()) {
            tCadastrarC = new TelaCadastrarCliente();
            tCadastrarC.pack();
            tCadastrarC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            tCadastrarC.setLocationRelativeTo(null);
            tCadastrarC.setVisible(true);
        }
        tCadastrarC.toFront();
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void criarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarComandaActionPerformed
        if (tCriarComanda == null || !tCriarComanda.isDisplayable()) {
            tCriarComanda = new TelaFazerVenda();
            tCriarComanda.pack();
            tCriarComanda.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            tCriarComanda.setLocationRelativeTo(null);
            tCriarComanda.setVisible(true);
        }
        tCriarComanda.toFront();
    }//GEN-LAST:event_criarComandaActionPerformed

    private void gerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRelatorioActionPerformed

        if (tGerarRelatorio == null || !tGerarRelatorio.isDisplayable()) {
            tGerarRelatorio = new TelaGerarRelatorio();
            tGerarRelatorio.pack();
            tGerarRelatorio.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            tGerarRelatorio.setLocationRelativeTo(null);
            tGerarRelatorio.setVisible(true);
        }
        tGerarRelatorio.toFront();
    }//GEN-LAST:event_gerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarCliente;
    private javax.swing.JMenuItem cadastrarProduto;
    private javax.swing.JMenuItem consultarCliente;
    private javax.swing.JMenuItem consultarProduto;
    private javax.swing.JMenuItem criarComanda;
    private javax.swing.JMenuItem gerarRelatorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenu menuVenda;
    // End of variables declaration//GEN-END:variables
}
